### PR TITLE
✨Table to show resources that reference a given ID

### LINKED ISSUE #18: View resources linked to particular resource
I think it might be useful for a user to view resources linked resources (resources which point to it). This would make use of FHIR search API's chained resource queries. 

What do you think? 

For example clicking on the blue link button below:
image

Would allow the user to see a table like this:

| Base Type | Profile | Count | 
----------- | ------- | ------ | 
Observation | PhenotypicFeature | 204
Specimen | None | 2
Condition | Diagnosis | 1

Clicking one of the rows above ^ would then result in a resource list view, similar to what we already display when a user clicks on a card from the home page.

### PR DESCRIPTION
**Pull request by abgeorge7**
Closes #18 
Click on a row from the details table will produce an additional table that shows which resources reference the given ID.

### CODE REVIEW

**Comment by abgeorge7** [comment]
Hm so what is the behavior if there is more than one of that type referencing the Patient?

**Comment by znatty22** [comment]
In your example, you had 1 Biosample referencing Patient. I just meant that instead of showing all possible Biospecimens, you should show the ones (however many there are) that reference the Patient instance.

**Comment by abgeorge7** [comment]
I'm wondering if it makes more sense to show the payloads of the reference resources? I guess my question is, is it a use case that a user would want to see just a snapshot of the  resource references? or do they just want to know the IDs? this kind of gets into filtering resources/cohorts building/etc and I just want to make sure that it fits in with our goal for this dashboard, if that makes sense.

Could also show the IDs and then clicking on an ID shows the payload?

**Comment by znatty22** [comment]
> Could also show the IDs and then clicking on an ID shows the payload?

👍

**Pull request merged**
